// sourced from https://docs.google.com/spreadsheets/d/1lsy7lIwBe-DWOi2PALZPf5DgXHx9MEvKfRw1GaWQkzg/edit#gid=9
module.exports = [
  "(Pick 2) _____ may pass, but _____ will last forever.",
  "(Pick 2) _____ will never be the same after _____.",
  "2 AM in the city that never sleeps. The door swings open and she walks in, legs up to here. Something in her eyes tells me she's looking for _____.",
  "(Pick 2) Adventure. Romance. _____. From Paramount Pictures, '_____.'",
  "Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. The time has come to commence Operation _____.",
  "As king, how will I keep the peasants in line?",
  "Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of _____.",
  "Do not fuck with me! I am literally _____ right now.",
  "(Pick 2) Every step towards _____ gets me a little bit closer to _____.",
  "(Pick 2) Forget everything you know about _____, because now we've supercharged it with _____!",
  "(Pick 2) Honey, I have a new role-play I want to try tonight! You can be _____, and I'll be _____.",
  "How am I compensating for my tiny penis?",
  "(Pick 2) I am become _____, destroyer of _____!",
  "I'm pretty sure I'm high right now, because I'm absolutely mesmerized by _____.",
  "I'm sorry, sir, but we don't allow _____ at the country club.",
  "(Pick 2) If you can't handle _____, you'd better stay away from _____.",
  "(Pick 2) In return for my soul, the Devil promised me _____, but all I got was _____.",
  "(Pick 2) In the beginning, there was _____. And the Lord said, 'Let there be _____.'",
  "It lurks in the night. It hungers for flesh. This summer, no one is safe from _____.",
  "Man, this is bullshit. Fuck _____.",
  "(Pick 2) Oprah's book of the month is '_____ For _____: A Story of Hope.'",
  "She's up all night for good fun. I'm up all night for _____.",
  "The Japanese have developed a smaller, more efficient version of _____.",
  "This is the prime of my life. I'm young, hot, and full of _____.",
  "(Pick 2) This year's hottest album is '_____' by _____.",
  "(Pick 2) We never did find _____, but along the way we sure learned a lot about _____.",
  "Wes Anderson's new film tells the story of a precocious child coming to terms with _____.",
  "What's fun until it gets weird?",
  "(Pick 3) You guys, I saw this crazy movie last night. It opens on _____, and then there's some stuff about _____, and then it ends with _____.",
  "You've seen the bearded lady! You've seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon _____!"
];
