// sourced from https://docs.google.com/spreadsheets/d/1lsy7lIwBe-DWOi2PALZPf5DgXHx9MEvKfRw1GaWQkzg/edit#gid=9
module.exports = [
  "And today's soup is Cream of _____.",
  "Armani suit: $1,000. Dinner for two at that swanky restaurant: $300. The look on her face when you surprise her with ______: priceless.",
  "Do the Dew with our most extreme flavor yet! Get ready for Mountain Dew _____!",
  "Do you lack energy? Does it sometimes feel like the whole world is _____ ? Zoloft.",
  "Don't forget! Beginning this week, Casual Friday will officially become '_____ Friday.'",
  "Get ready for the movie of the summer! One cop plays by the book. The other's only interested in one thing: _____.",
  "Having the worst day EVER. #_____",
  "Heed my voice, mortals! I am the god of _____ , and I will not tolerate _____!",
  "Help me doctor, I've got _____ in my butt!",
  "Here at the Academy for Gifted Children, we all students to explore _____ at their own pace.",
  "Hi MTV! My name is Kendra, I live in Malibu, I'm into _____, and I love to have a good time.",
  "Hi, this is Jim from accounting. We noticed a $1,200 charge labeled '_____.' Can you explain?",
  "I don't mean to brag, but they call me the Micheal Jordan of _____.",
  "In his farewell address, George Washington famously warned Americans about the dangers of _____.",
  "In his new action comedy, Jackie Chan must fend off ninjas while also dealing with _____.",
  "Life's pretty tough in the fast lane. That's why I never leave the house without _____.",
  "Now in bookstores: 'The Audacity of _____' by Barack Obama.",
  "(Pick 2) Patient presents with _____ . Likely a result of _____ .",
  "(Pick 2) Well if ______ is good enough for _____, it's good enough for me.",
  "Well what do you have to say for yourself, Casey? This is the third time you've been sent to the principal's office for ______.",
  "What killed my boner?",
  "What's making things awkward in the sauna?",
  "WHOOO! God damn I love _____!",
  "Why am I broke?",
  "Yo' mama's so fat she _____!"
];