module.exports = [
  'What’s fun until it gets weird?',
  'In the beginning, there was _____. And the Lord said, “Let there be _____.”',
  'Wes Anderson’s new film tells the story of a precocious child coming to terms with _____.',
  '_____ will never be the same after _____.',
  'I’m sorry, sir, but we don’t allow ______ at the country club.',
  'How am I compensating for my tiny penis?',
  'You’ve seen the bearded lady! You’ve seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon _____!',
  'We never did find _____, but along the way we sure learned a lot about _____.',
  'She’s up all night for good fun. I’m up all night for _____.',
  '_____ may pass, but _____ will last forever.',
  'Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of _____.',
  'Man, this is bullshit. Fuck _____.',
  'You guys, I saw this crazy movie last night. It opens on ______, and then there’s some stuff about ______, and then it ends with _____.',
  'In return for my soul, the Devil promised me _____, but all I got was _____.',
  'The Japanese have developed a smaller, more efficient version of _____.',
  'Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. That time has come to commence Operation _____.',
  'This is the prime of my life. I’m young, hot, and full of _____.',
  'I’m pretty sure I’m high right now, because I’m absolutely mesmerized by _____.',
  'It lurks in the night. It hungers for flesh. This summer, no one is safe from ______.',
  'If you can’t handle _____, you’d better stay away from _____.',
  'Forget everything you know about _____, because now we’ve supercharged it with ______!',
  'Honey, I have a new role-play I want to try tonight! You can be _____, and I’ll be _____.',
  'This year’s hottest album is “_____” by _____.',
  'Every step towards _____ gets me a little bit closer to _____.',
  'Oprah’s book of the month is “_____ For _____: A Story of Hope.”',
  'Do not fuck with me! I am literally _____ right now.',
  '2 AM in the city that never sleeps. The door swings open and she walks in, legs up to here. Something in her eyes tells me she’s looking for _____.',
  'As king, how will I keep the peasants in line?',
  'Adventure. Romance. _____. From Paramount Pictures, “_____.”',
  'I am become _____, destroyer of _____!'
];