// sourced from https://docs.google.com/spreadsheets/d/1lsy7lIwBe-DWOi2PALZPf5DgXHx9MEvKfRw1GaWQkzg/edit#gid=9
module.exports = [
  "(Pick 2) _____ would be woefully incomplete without _____.",
  "A remarkable new study has shown that chimps have evolved their own primitive version of _____.",
  "After months of debate, the Occupy Wall Street General Assembly could only agree on 'More _____!'",
  "(Pick 2) Before _____, all we had was _____.",
  "Before I run for president, I must destroy all evidence of my involvement with _____.",
  "Charades was ruined for me forever when my mom had to act out _____.",
  "During his midlife crisis, my dad got really into _____.",
  "Everyone down on the ground! We don't want to hurt anyone. We're just here for _____.",
  "(Pick 2) I spent my whole life working toward _____, only to have it ruined by _____.",
  "(Pick 3) I went from _____ to _____, all thanks to _____.",
  "(Pick 2) If God didn't want us to enjoy _____, he wouldn't have given us _____.",
  "In his newest and most difficult stunt, David Blaine must escape from _____.",
  "Little Miss Muffet Sat on a tuffet, Eating her curds and _____.",
  "Members of New York's social elite are paying thousands of dollars just to experience _____.",
  "My country, 'tis of thee, sweet land of _____.",
  "(Pick 2) My mom freaked out when she looked at my browser history and found _____.com/_____.",
  "My new favorite porn star is Joey '_____' McGee.",
  "Next time on Dr. Phil: How to talk to your child about _____.",
  "Only two things in life are certain: death and _____.",
  "The Five Stages of Grief: denial, anger, bargaining, _____, acceptance.",
  "The healing process began when I joined a support group for victims of _____.",
  "The votes are in, and the new high school mascot is _____.",
  "This is your captain speaking. Fasten your seatbelts and prepare for _____.",
  "This month's Cosmo: 'Spice up your sex life by bringing _____ into the bedroom.'",
  "Tonight on 20/20: What you don't know about _____ could kill you.",
  "What's harshing my mellow, man?",
  "(Pick 2) You haven't truly lived until you've experienced _____ and _____ at the same time.",
  "Your persistence is admirable, my dear Prince. But you cannot win my heart with _____ alone."
];