module.exports = [
  'I work my ass off all day for this family, and this what I come home to? _____!?',
  'I have a strict policy. First date, dinner. Second date, kiss. Third date, _____.',
  'When I was a kid we used to play Cowboys and _____.',
  'This is America. If you don’t work hard, you don’t succeed. I don’t care if you’re black, white, purple, or _____.',
  'You Won’t Believe These 15 Hilarious _____ Bloopers!',
  'James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: _____.',
  'Don’t worry, kid. It gets better. I’ve been living with _____ for 20 years.',
  'My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and _____.',
  'Behind every powerful man is _____.',
  'You are not alone. Millions of Americans struggle with _____ every day.',
  'Come to Dubai, where you can relax in our world-famous spas, experience the nightlife, or simply enjoy _____ by the poolside.',
  '“This is madness!” “No. THIS IS _____!”',
  'Listen, Gary, I like you. But if you want that corner office, you’re going to have to show me _____.',
  'I went to the desert and ate of the peyote cactus. Turns out my spirit animal is _____.',
  'And would you like those buffalo wings mild, hot, or _____?',
  'The six things I could never do without: oxygen, facebook, chocolate, netflix, friends, and _____ LOL!',
  'Why won’t you make love to me anymore? Is it _____?',
  'Puberty is a time of change. You might notice hair growing in new places. You might develop an interest in _____. This is normal.',
  'I’m sorry, Mrs. Chen, but there was nothing we could do. At 4:15 this morning, your son succumbed to _____.',
  'I’m Miss Tennessee, and if I could make the world better by changing one thing, I would get rid of _____.',
  'Tonight, we will have sex. And afterwards, if you’d like, a little bit of _____.',
  'Everybody join hands and close your eyes. Do you sense that? That’s the presence of _____ in this room.',
  'To become a true Yanomamo warrior, you must prove that you can withstand _____ without crying out.',
  'Y’all ready to get this thing started? I’m Nick Cannon, and this is America’s Got _____.',
  'If you had to describe me, the Card Czar, using only one of the cards in your hand, which one would it be?'
];