// sourced from https://docs.google.com/spreadsheets/d/1lsy7lIwBe-DWOi2PALZPf5DgXHx9MEvKfRw1GaWQkzg/edit#gid=9
module.exports = [
  "(Pick 3) _____ + _____ = _____.",
  "(Pick 2) _____ is a slippery slope that leads to _____.",
  "_____: good to the last drop.",
  "_____: kid-tested, mother-approved.",
  "_____. Betcha can't have just one!",
  "_____. High five, bro.",
  "_____. It's a trap!",
  "A romantic, candlelit dinner would be incomplete without _____.",
  "After the earthquake, Sean Penn brought _____ to the people of Haiti.",
  "Alternative medicine is now embracing the curative powers of _____.",
  "(Pick 2) And the Academy Award for _____ goes to _____.",
  "But before I kill you, Mr. Bond, I must show you _____.",
  "Coming to Broadway this season, _____: The Musical.",
  "Daddy, why is mommy crying?",
  "Dear Abby, I'm having some trouble with _____ and would like your advice.",
  "During sex, I like to think about _____.",
  "(Pick 2) For my next trick, I will pull _____ out of _____.",
  "Here is the church Here is the steeple Open the doors And there is _____.",
  "How am I maintaining my relationship status?",
  "How did I lose my virginity?",
  "I drink to forget _____.",
  "I got 99 problems but _____ ain't one.",
  "(Pick 2) I never truly understood _____ until I encountered _____.",
  "I'm sorry, Professor, but I couldn't complete my homework because of _____.",
  "(Pick 2) In a world ravaged by _____, our only solace is _____.",
  "In L.A. County Jail, word is you can trade 200 cigarettes for _____.",
  "(Pick 2) In M. Night Shyamalan's new movie, Bruce Willis discovers that _____ had really been _____ all along.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time.",
  "Instead of coal, Santa now gives the bad children _____.",
  "It’s a pity that kids these days are all getting involved with _____.",
  "Life for American Indians was forever changed when the White Man introduced them to _____.",
  "(Pick 2) Lifetime® presents '_____: the Story of _____.'",
  "Make a haiku.",
  "Maybe she's born with it. Maybe it's _____.",
  "MTV's new reality show features eight washed-up celebrities living with _____.",
  "Next from J.K. Rowling: Harry Potter and the Chamber of _____.",
  "Next on ESPN2: The World Series of _____.",
  "(Pick 2) Step 1: _____. Step 2: _____. Step 3: Profit.",
  "(Pick 2) That's right, I killed _____. How, you ask? _____.",
  "The class field trip was completely ruined by _____.",
  "This is the way the world ends This is the way the world ends Not with a bang but with _____.",
  "TSA guidelines now prohibit _____ on airplanes.",
  "War! What is it good for?",
  "What are my parents hiding from me?",
  "What did I bring back from Mexico?",
  "What did the US airdrop to the children of Afghanistan?",
  "What did Vin Diesel eat for dinner?",
  "What ended my last relationship?",
  "What gives me uncontrollable gas?",
  "What helps Obama unwind?",
  "What is Batman's guilty pleasure?",
  "What never fails to liven up the party?",
  "What will always get you laid?",
  "What would grandma find disturbing, yet oddly charming?",
  "What's a girl's best friend?",
  "What's my secret power?",
  "What's Teach for America using to inspire inner city students to succeed?",
  "What's that smell?",
  "What's that sound?",
  "What's the next Happy Meal® toy?",
  "What's there a ton of in heaven?",
  "When I am a billionare, I shall erect a 50-foot statue to commemorate _____.",
  "When I am President of the United States, I will create the Department of _____.",
  "(Pick 2) When I was tripping on acid, _____ turned into _____.",
  "When Pharaoh remained unmoved, Moses called down a Plague of _____.",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____.",
  "White people like _____.",
  "Why am I sticky?",
  "Why can't I sleep at night?",
  "Why do I hurt all over?",
  "_____. That's how I want to die.",
  "BILLY MAYS HERE FOR _____.",
  "During his childhood, Salvador Dali produced hundreds of paintings of _____.",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with _____.",
  "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
  "In Michael Jackson's final moments, he thought about _____.",
  "Major League Baseball has banned _____ for giving players an unfair advantage.",
  "(Pick 2) Rumor has it that Vladimir Putin's favorite dish is _____ stuffed with _____.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to _____.",
  "The Smithsonian Museum of Natural History has just opened an interactive exhibit on _____.",
  "What am I giving up for Lent?",
  "What do old people smell like?",
  "What does Dick Cheney prefer?",
  "What don't you want to find in your Chinese food?",
  "What gets better with age?",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "What's my anti-drug?",
  "What's the most emo?",
  "What's the new fad diet?",
  "What's the next superhero/sidekick duo?",
  "_____. That was so metal.",
  "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to _____.",
  "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: _____.",
  "Fun tip! When your man asks you to go down on him, try surprising him with _____ instead.",
  "Hey Reddit! I'm _____. Ask me anything.",
  "I get by with a little help from _____.",
  "I'm going on a cleanse this week. Nothing but kale juice and _____.",
  "(Pick 2) Introducing the amazing superhero/sidekick duo! It's _____ and _____!",
  "Introducing X-Treme Baseball! It's like baseball, but with _____!",
  "Just saw this upsetting video! Please retweet!! #stop_____",
  "Kids, I don't need drugs to get high. I'm high on _____.",
  "Now at the Smithsonian: an interactive exhibit on _____.",
  "The new Chevy Tahoe. With the power and space to take _____ everywhere you go.",
  "(Pick 2) They said we were crazy. They said we couldn't put _____ inside of _____. They were wrong.",
  "Today on /Maury/: 'Help! My son is _____!'",
  "Uh, hey guys, I know this was my idea, but I'm having serious doubts about _____.",
  "Well if you'll excuse me, gentlemen, I have a date with _____.",
  "What don't you want to find in your Kung Pao chicken?",
  "What is George W. Bush thinking about right now?",
  "What made my first kiss so awkward?",
  "_____: Once you pop, the fun don't stop!",
  "_____? Jim'll fix it!",
  "_____. That's why mums go to Iceland.",
  "_____? There's an app for that.",
  "After Hurricane Katrina, Sean Penn brought _____ to all the people of New Orleans.",
  "Airport security guidelines now prohibit _____ on airplanes.",
  "(Pick 2) And the BAFTA for _____ goes to _____.",
  "Anthropologists have recently discovered a primitive tribe that worships _____.",
  "(Pick 2) Channel 4 presents _____, the story of _____.",
  "Channel 5's new reality show features eight washed-up celebrities living with _____.",
  "Coming to the West End this year, _____: The Musical.",
  "Daddy, why is mummy crying?",
  "Dear Agony Aunt, I'm having some trouble with _____ and I need your advice.",
  "Due to a PR fiasco, Walmart no longer offers _____.",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____.",
  "I wish I hadn't lost the instruction manual for _____.",
  "I'm sorry,Sir, but I couldn't complete my homework because of _____.",
  "In 1,000 years, when paper money is but a distant memory, _____ will be our currency.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____.",
  "In her latest feature-length film, Tracy Beaker struggles with _____ for the first time.",
  "(Pick 2) In his new summer comedy, Rob Schneider is _____ trapped in the body of _____.",
  "In Wormwood Scrubs, word is you can trade 200 cigarettes for _____.",
  "Instead of coal, Father Christmas now gives bad children _____.",
  "Life was difficult for cavemen before _____.",
  "Next on Sky Sports: The World Championship of _____.",
  "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and _____.",
  "O Canada, we stand on guard for _____.",
  "Sorry everyone, I just _____.",
  "The Natural History Museum has just opened an interactive exhibit on _____.",
  "The school field trip was completely ruined by _____.",
  "The TFL apologizes for the delay in train service due to _____.",
  "The theme for next year's Eurovision Song Contest is 'We are _____.'",
  "The U.S. has begun airdropping _____ to the children of Afghanistan.",
  "Today on The Jeremy Kyle Show: 'Help! My son is _____!'",
  "What are school administrators using to curb rampant teenage pregnancy?",
  "What did I bring back from Amsterdam?",
  "What kept Margaret Thatcher busy in her waning years?",
  "What's the crustiest?",
  "What's the next superhero?",
  "When I am Prime Minister of the United Kingdom, I will create the Ministry of _____.",
  "When I'm in prison, I'll have _____ smuggled in.",
  "Who stole the cookies from the cookie jar?"
];